### ISSUE TITLE
Ability Choice Mod unable to switch modes, settings not working.

### ISSUE THREAD

**Issue by Marymatician** [doombubbles/ability-choice#1]
![image](https://user-images.githubusercontent.com/73314377/188710651-b3726e0f-81ea-4524-9e73-df756e0b999a.png)

Going into the mod settings to change all modes doesn't work, returning that error, and right-clicking the upgrade to change it doesn't work either.

**Comment by doombubbles** [comment]
Now fixed with latest version 2.0.2 for Btd6 v32.3
