### ISSUE TITLE
ability choice not working

### ISSUE THREAD

**Issue by Crandall0** [doombubbles/ability-choice#4]
![image](https://github.com/doombubbles/ability-choice/assets/81304240/e6525b2f-c23d-4719-b494-ed73dfa9459e)

even though abilitychoice for glue gunner is set to blue, it still functions as if it has the regular yellow activatable ability. this is the same for all my towers.

**Comment by Crandall0** [comment]
![image](https://github.com/doombubbles/ability-choice/assets/81304240/841feaef-8a7e-41ae-9c5d-c65279354848)

**Comment by doombubbles** [comment]
Fixed with latest release https://github.com/doombubbles/ability-choice/releases/tag/3.0.2

**Comment by Crandall0** [comment]
:)
