### ISSUE TITLE
Ability choice makeing game crash

### ISSUE THREAD

**Issue by NotASpicyGerman** [doombubbles/ability-choice#8]
I was booting up btd6 with melon loader but when it got to the loading stage but as it reached 9/9 the game just shut down so I tried it again but same thing happened, so I checked melon for updates and none so I reinstalled and same thing so I reinstalled the whole game same thing so I deleted the mods one by one while trying to start the game each time till I got to ability choice and when I deleted it the game would load so I installed all the mods again except ability choice and the game ran just fine so I reinstalled ability choice and I started crashing again.

**Comment by doombubbles** [comment]
There’s a bug with MelonLoader 0.6.5 that makes a small thing functionality that Ability Choice makes use of cause a game crash. Downgrading to 0.6.1 will fix it

**Comment by NotASpicyGerman** [comment]
Ok thank you
